server:
  port: 8002
spring:
  application:
    name: cloud-consumer-order
  data:
    mongodb:
      password: '123456'
      username: tp
      database: account
      host: localhost
      port: 27017

  cloud:
    alibaba:
      seata:
        tx-service-group: test_group
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
        port: 8719
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0



