server:
  port: 8001
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: student719
      username: tp
      password: 123456
      authentication-database: admin
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 30MB